### ISSUE TITLE
Prepare for monorepo

### ISSUE THREAD

**Issue by ricardoboss** [ricardoboss/dart_kiota#14]
As many other Kiota implementations, this repository will host the abstractions alongside some implementations for those.

Currently, the repository only hosts the `kiota_abstractions` package.
In the future, other packages might be added to this repository, for example:

- `kiota_http`: Implements an API client using the Dart [`http`](https://pub.dev/packages/http) package
- `kiota_dio`: Implements an API client using [`dio`](https://pub.dev/packages/dio)
- `kiota_serialization_json`: Implements JSON serialization using any approach described in [the flutter docs](https://docs.flutter.dev/data-and-backend/serialization/json) (TBD)
- `kiota_serialization_form`: Implements form serialization
- `kiota_serialization_text`: Implements text serialization
- `kiota_serialization_multipart`: Implements multipart serialization

**Comment by ricardoboss** [comment]
@baywet I took some inspiration from the typescript repo to come up with this structure. What do you think? Am I missing some common package?

Another thing that will be interesting is the JSON serialization. That is because Dart doesn't have reflection. I linked to common solutions in Flutter, like [`json_serializable`](https://pub.dev/packages/json_serializable), which generates de-/serializers for each model, which makes it non-generic.

**Comment by baywet** [comment]
This looks great!
I do have a couple of questions:
- you're planning to roll out 2 http implementations: http and dio, correct? Could we scope things to a single one for now to reduce the implementation burden you'll have to go through to begin with? (ideally the most popular that supports defining middleware handlers in the client)
- no authentication implementation planned so far for OAuth? (our friends in Azure and Entra don't seem to be publishing msal/azure identity for dart)

**Comment by ricardoboss** [comment]
> you're planning to roll out 2 http implementations: http and dio, correct?

I mainly wanted to highlight (at least for my own understanding) where to draw the line for the abstraction. `dio` is just a different popular HTTP library for Dart, that's the only reason I listed it here. I'd prefer focussing on Darts `http` package because I know how to use it. `dio` has better support for middleware, I think... Need to investigate.

> no authentication implementation planned so far for OAuth

I must admit that I my abilities and knowledge regarding OAuth are... lacking. For (secure and correct!) auth implementations beyond query/api key I probably need some guidance. But I'm sure it's not impossible for me to create a first implementation.
