### ISSUE TITLE
missing backing store aspects

### ISSUE THREAD

**Issue by baywet** [ricardoboss/dart_kiota#6]
This doesn't need to be implemented in the language to start playing with the generation, but I thought I'd create an issue to track that.

**Comment by ricardoboss** [comment]
@baywet do you think #10 implemented enough to provide a solid foundation? Otherwise we'll just keep this open

**Comment by baywet** [comment]
I've run a comparison with the dotnet implementation, here is the outline of the differences, I think a quick PR could fix all of that:
- the singleton needs to be settable
- backed model and backing store need to be interfaces (unless there's some dart limitation I'm not aware of?)

**Comment by ricardoboss** [comment]
> backed model and backing store need to be interfaces (unless there's some dart limitation I'm not aware of?)

Dart doesn't have interfaces. Instead it has abstract classes which you can either extend or implement. Implementing an abstract class requires you to implement all members yourself while extending it allows you to inherit already implemented members.

**Comment by baywet** [comment]
Thanks for the explanation here. I think we're good then given the language specifics. Closing.
